#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!
sudo apt-get updata -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start 